### ISSUE TITLE
Error in file declare module in typescript

### ISSUE THREAD

**Issue by mariosantosdev** [Marvinified/use-file-upload#2]
![image](https://user-images.githubusercontent.com/34768052/98955885-34140900-24de-11eb-81bd-fdcb4f8e7467.png)
That error, happen when I started project react using typescript

**Comment by marvinified** [comment]
@nvrsantos Can you please provide more context, I couldn't reproduce your error.

**Comment by nvrsantos** [comment]
I don't why that happen, but I fixed tempory. I Created an new declaration.
![image](https://user-images.githubusercontent.com/34768052/99106736-7b27fa00-25c3-11eb-88bf-ca738455afc2.png)

@Marvinified You think better I close the issue ?

**Comment by nvrsantos** [comment]
I so sorry, My code just was poor

**Comment by mariosantosdev** [comment]
I dont undestand why that happen, but I install the version 1.0.8 and created an custom declare file, and it has been temporarily fixed.

![image](https://user-images.githubusercontent.com/34768052/99151936-5e4ffd00-267d-11eb-8d0a-6065358d2d02.png)

**Comment by marvinified** [comment]
@nvrsantos I will look into this and try to make a fix but I would need more info about your code setup to be able to reproduce the error. Thanks.

**Comment by mariosantosdev** [comment]
What kind of information do u need?

**Comment by mumumu-ko** [comment]
I have the same problem in Ver1.0.9.
I solved it by defining Type in `index.d.ts`.
See below.

```
declare module "use-file-upload" {
    type FileUpload = {
        source: URL;
        name: string;
        size: number;
        file: File;
    }

    type Callback = (file: FileUpload | [FileUpload]) => void;

    const useFileUpload: () => [
       　file<FileUpload | [FileUpload]>,
       　selectFiles<({ accept: string, multiple: boolean }, callback: Callback) => void>,
   　]
}
```

Type definition issues in newer versions of React...?
Thnaks.

**Comment by norbiu** [comment]
Any update on this?

**Comment by intergalactic-overlords** [comment]
create a PR to fix this: https://github.com/Marvinified/use-file-upload/pull/4

**Comment by mariosantosdev** [comment]
Great job!
